version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  backend:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      supabase-db:
        condition: service_healthy
      supabase-auth:
        condition: service_started

  supabase-db:
    image: supabase/postgres:15.1.0.72
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./supabase/volumes/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  supabase-auth:
    image: supabase/gotrue:v2.150.0
    ports:
      - "9999:9999"
    environment:
      API_EXTERNAL_URL: http://auth:9999
      GOTRUE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
      GOTRUE_API_HOST: 0.0.0.0
    env_file:
      - .env
