name: Apply DB Migrations

on:
  push:
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/db-migrate.yml'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      db:
        image: supabase/postgres:15.1.0.72
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run migrations
        run: ./scripts/apply_migrations.sh
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASS: postgres
